require("config.lazy")
vim.cmd([[colorscheme tokyonight]])
require("config.keymaps")
require("config.autocmds")
require("config.options")
require("config.vim-lsp-config")
require("scripts.clipboard-functions")
require("scripts.toggle-quickfix")
require("scripts.yank-buffer-path")
require("scripts.lazygit-terminal")
require("scripts.swap-true-false-keywords")
require("scripts.various-utils")
require("scripts.snacks-path-insert")
require("scripts.create-float")
require("scripts.flip-flop-comments")
require("scripts.maximize-window")
