_G.OnWindows = vim.fn.has("win32") == 1 or vim.fn.has("win64") == 1
_G.Logger = require("config.custom-logging")
Logger.init()
Logger.set_level("DEBUG")
_G.RepeatablePairs = require("config.repeatable-pairs")
RepeatablePairs.setup()
require("config.lazy")
vim.cmd([[colorscheme tokyonight-storm]])
require("config.keymaps")
require("config.autocmds")
require("config.options")
require("config.highlight-groups")
require("config.lsp-settings")
require("config.custom-logging")
require("scripts.clipboard-functions")
require("scripts.toggle-quickfix")
require("scripts.yank-buffer-path")
require("scripts.lazygit-terminal")
require("scripts.swap-true-false-keywords")
require("scripts.various-utils")
require("scripts.create-float")
require("scripts.flip-flop-comments")
require("scripts.maximize-window")
require("scripts.delete-mark")
